MPD_PORT = 6600
MPD_IP = "localhost"

PYMC_BLOCK = 4
# PLAYLIST_NUMBER = 0
TRACK_NUMBER = 1
PLAYLIST_REPEAT = 2
PLAYLIST_SHUFFLE = 3
TRACK_TIME_MSB = 4
TRACK_TIME_LSB = 5

PLAYLIST_PATH = 'playlists.json'
